### ISSUE TITLE
Can I fork this Project [Question]

### ISSUE THREAD

**Issue by SkyNetCloud** [lociii/overwolf-homeassistant-webhook#1]
Do I have your permission to fork this project and try my hand at getting it uploaded to overwolf app store cuz it wasn't on there

**Comment by SkyNetCloud** [comment]
Cuz I was hoping to use this app with my home assistant system

**Comment by lociii** [comment]
This is work on progress and not yet functional.

Feel free to open merge requests if you can support. I planned to finalize it over the Christmas holidays. Ideally there shouldn't be multiple apps on the overwolf store.

**Comment by lociii** [comment]
It's in a usable state now. However I will need to prepare the [store assets](https://overwolf.github.io/start/submit-your-app#prepare-your-store-assets) before submitting it. If you have an overwolf developer account, you can build the app and load it unpacked to try it out.

**Comment by SkyNetCloud** [comment]
I don't have a dev account so I'll just wait until you upload it to the app store

**Comment by lociii** [comment]
Submitted for review

**Comment by SkyNetCloud** [comment]
> Submitted for review

any update on the review?

**Comment by lociii** [comment]
According to https://overwolf.github.io/start/submit-your-app it will take 1-2 weeks. Assume a bit longer as the staff may also celebrate Christmas and new year.
Will update as soon as I have news.

**Comment by SkyNetCloud** [comment]
guessing they still haven't approved it yet.

**Comment by lociii** [comment]
Correct.
One of their team members wants to properly tests it but didn't use HomeAssistant before.

**Comment by lociii** [comment]
The app finally got approved but I'm having issues uploading the OPK file to the store backend. Waiting for feedback from Overwolf now.

**Comment by SkyNetCloud** [comment]
I hope they help you fix it :D

**Comment by lociii** [comment]
Hooray, it's live! https://www.overwolf.com/app/BinaryBurger-HomeAssistant_Game_Events
