### ISSUE TITLE
Can't see game events on event log window

### ISSUE THREAD

**Issue by Tomerlm** [lociii/overwolf-homeassistant-webhook#8]
****Description****

I'm opening the app and starting a game, expecting to see events starting to fire up in the events log. 

this issue is problematic because this is the only way for me to know the app is doing its job.

**Expected**

When the app is running, I'm expecting to see a flow of logs while playing a game (for example, LoL, PUBG etc)

**Comment by lociii** [comment]
Hey Tomer,

thanks for getting in contact.
Is there any output when the app is running? Can you please attach a screenshot of your settings?
Can you please also provide a screenshot of the webhook config in Home Assistant?

I regularly use it with PUBG and it works flawlessly when set up correctly.

Best, Jens

**Comment by Tomerlm** [comment]
Hey, thanks for the replay :) 
those are my settings
![image](https://github.com/lociii/overwolf-homeassistant-webhook/assets/34571580/ed339191-70de-40c2-9584-557725c34f64)

about HA, haven't done anything special, just installed the integration as the instructions suggested. not sure where to take the screenshot from. but anyway. I only concered about the overwolf app side, and expected the logs to start appearing even if it haven't been successfully sent to HA. 

Ideally, I would see an event, with status code by its side to know the response code from HA

**Comment by lociii** [comment]
That's wild. Here's a screenshot from my system.  
![image](https://github.com/lociii/overwolf-homeassistant-webhook/assets/366967/46d6d3bc-aacc-4c47-973a-b033802d8376)

I can also see people play all kinds of games with the app running.  
![image](https://github.com/lociii/overwolf-homeassistant-webhook/assets/366967/c5b99d4e-d871-4011-a824-7c9546dcccb1)

What version of Overwolf are you using?  
It works for me on 0.241.0.10

As this app is not doing any more than waiting for Overwolf to send events that it can capture and forward, it'll be hard for me to debug why Overwolf is not sending anything.

**Comment by Tomerlm** [comment]
looks nice on your side! I will try to debug my overwolf app, maybe its permissions issue? (my version is same as yours, latest)

**Comment by lociii** [comment]
Can you try another app that relies on game events and see if it works?

**Comment by Tomerlm** [comment]
It suddenly started to work! however, there's a different issue. it seems like the app take up ALOT of memory for what it does. I think it might be due to the fact the logs are persisted in the app. after a game of LoL it took around 2GB of memory, and when I closed the app it went down immediately.

**Comment by lociii** [comment]
Good point. What log limit would you deem reasonable? I could clear old log lines once we reach a certain line count.

**Comment by mxc42** [comment]
A log limit would be good, I've only used it with Riot games (League and Valorant) and there's a ton of output over time. After a couple hours the window freezes up. For my use case I'd be fine with just a checkbox to enable logging, or a limit of 100 lines or so. If I need logs I've been using the event listener built into Home Assistant anyways.

**Comment by lociii** [comment]
Version 1.2.0 is now under review with Overwolf and will be released soon.  
See https://github.com/lociii/overwolf-homeassistant-webhook/blob/main/CHANGELOG.md

**Comment by lociii** [comment]
Update has been released.
@Tomerlm Would be great if you could update your review 😄

**Comment by mxc42** [comment]
1.2.0 seems to fix the issues I've had with the window freezing so far, haven't tested very substantially yet but the last couple weeks it was very buggy and events were getting sent late if ever. So far none of that, nicely done!
